"""
Seed inicial de recetas con cantidades y tiempos por paso.
Todas las recetas estan calibradas para sus "porciones" base.
El frontend re-escala las cantidades segun el usuario.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from db import init_db, get_conn, insertar_receta  # noqa: E402


def ing(nombre, cantidad=0, unidad="al gusto"):
    return {"nombre": nombre, "cantidad": cantidad, "unidad": unidad}


def paso(texto, tiempo_minutos=None):
    return {"texto": texto, "tiempo_minutos": tiempo_minutos}


RECETAS = [
    {
        "nombre": "Arroz con pollo",
        "dificultad": "facil",
        "tiempo_minutos": 40,
        "porciones": 4,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("pollo", 500, "g"),
            ing("arroz", 300, "g"),
            ing("cebolla", 1, "unidad"),
            ing("ajo", 2, "dientes"),
            ing("agua", 600, "ml"),
            ing("sal", 1, "cdita"),
            ing("aceite", 2, "cdas"),
        ],
        "ingredientes_opcionales": [
            ing("morron", 1, "unidad"),
            ing("zanahoria", 1, "unidad"),
            ing("perejil", 0, "al gusto"),
        ],
        "pasos": [
            paso("Cortar el pollo en trozos medianos y salpimentar.", 3),
            paso("Picar la cebolla y el ajo finamente.", 3),
            paso("Sofreir la cebolla y el ajo en una olla con aceite hasta que esten transparentes.", 4),
            paso("Agregar el pollo y dorar de todos lados.", 5),
            paso("Sumar el arroz, mezclar y agregar el agua caliente.", 2),
            paso("Tapar y cocinar a fuego bajo hasta que el arroz absorba el liquido.", 20),
        ],
    },
    {
        "nombre": "Tortilla de papas",
        "dificultad": "facil",
        "tiempo_minutos": 35,
        "porciones": 3,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("papa", 600, "g"),
            ing("huevo", 5, "unidades"),
            ing("cebolla", 1, "unidad"),
            ing("aceite", 100, "ml"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("queso", 80, "g"),
        ],
        "pasos": [
            paso("Pelar y cortar las papas en rodajas finas.", 5),
            paso("Picar la cebolla en juliana.", 2),
            paso("Freir las papas y la cebolla en aceite hasta que esten tiernas.", 15),
            paso("Batir los huevos en un bol grande con sal.", 2),
            paso("Escurrir las papas y mezclarlas con los huevos.", 1),
            paso("Cocinar en sarten antiadherente 4 minutos por lado.", 8),
        ],
    },
    {
        "nombre": "Pasta con salsa de tomate",
        "dificultad": "facil",
        "tiempo_minutos": 20,
        "porciones": 2,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("fideos", 250, "g"),
            ing("salsa de tomate", 400, "ml"),
            ing("ajo", 2, "dientes"),
            ing("aceite", 2, "cdas"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("queso rallado", 50, "g"),
            ing("albahaca", 0, "al gusto"),
            ing("cebolla", 1, "unidad"),
        ],
        "pasos": [
            paso("Poner una olla con agua y sal a hervir.", 8),
            paso("Cocinar la pasta segun las instrucciones del paquete.", 9),
            paso("En una sarten, sofreir el ajo picado en aceite.", 2),
            paso("Agregar la salsa de tomate y cocinar a fuego bajo.", 5),
            paso("Escurrir la pasta y mezclar con la salsa.", 1),
            paso("Servir con queso rallado si se desea.", 1),
        ],
    },
    {
        "nombre": "Revuelto de huevos con verduras",
        "dificultad": "facil",
        "tiempo_minutos": 15,
        "porciones": 2,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("huevo", 4, "unidades"),
            ing("cebolla", 1, "unidad"),
            ing("tomate", 1, "unidad"),
            ing("aceite", 1, "cda"),
            ing("sal", 1, "pizca"),
        ],
        "ingredientes_opcionales": [
            ing("morron", 1, "unidad"),
            ing("queso", 50, "g"),
            ing("perejil", 0, "al gusto"),
        ],
        "pasos": [
            paso("Picar la cebolla y el tomate en cubos pequenos.", 3),
            paso("Calentar aceite en una sarten y sofreir la cebolla.", 3),
            paso("Agregar el tomate y cocinar.", 3),
            paso("Batir los huevos con sal y verter en la sarten.", 1),
            paso("Revolver suavemente hasta que cuajen.", 4),
        ],
    },
    {
        "nombre": "Pollo al horno con papas",
        "dificultad": "facil",
        "tiempo_minutos": 60,
        "porciones": 4,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("pollo", 1, "unidad"),
            ing("papa", 800, "g"),
            ing("ajo", 4, "dientes"),
            ing("limon", 1, "unidad"),
            ing("aceite", 3, "cdas"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("oregano", 1, "cdita"),
            ing("cebolla", 1, "unidad"),
        ],
        "pasos": [
            paso("Precalentar el horno a 200 grados.", 10),
            paso("Cortar las papas en gajos y disponer en una fuente.", 5),
            paso("Salpimentar el pollo y agregar ajo picado y jugo de limon.", 5),
            paso("Colocar el pollo sobre las papas y rociar con aceite.", 2),
            paso("Hornear hasta que el pollo este dorado.", 45),
        ],
    },
    {
        "nombre": "Ensalada mixta",
        "dificultad": "facil",
        "tiempo_minutos": 10,
        "porciones": 2,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("lechuga", 1, "unidad"),
            ing("tomate", 2, "unidades"),
            ing("cebolla", 0.5, "unidad"),
            ing("aceite", 2, "cdas"),
            ing("vinagre", 1, "cda"),
            ing("sal", 1, "pizca"),
        ],
        "ingredientes_opcionales": [
            ing("zanahoria", 1, "unidad"),
            ing("huevo", 2, "unidades"),
        ],
        "pasos": [
            paso("Lavar y cortar la lechuga en trozos.", 3),
            paso("Cortar el tomate en cubos.", 2),
            paso("Cortar la cebolla en juliana fina.", 2),
            paso("Mezclar todo en un bol y condimentar con aceite, vinagre y sal.", 2),
        ],
    },
    {
        "nombre": "Sopa de verduras",
        "dificultad": "facil",
        "tiempo_minutos": 40,
        "porciones": 4,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("zanahoria", 2, "unidades"),
            ing("papa", 2, "unidades"),
            ing("cebolla", 1, "unidad"),
            ing("calabaza", 300, "g"),
            ing("agua", 1.5, "l"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("fideos", 100, "g"),
            ing("perejil", 0, "al gusto"),
        ],
        "pasos": [
            paso("Pelar y cortar todas las verduras en cubos medianos.", 8),
            paso("Rehogar la cebolla en una olla con aceite.", 4),
            paso("Agregar el resto de las verduras y cubrir con agua.", 2),
            paso("Cocinar hasta que las verduras esten tiernas.", 25),
            paso("Salpimentar y servir caliente.", 1),
        ],
    },
    {
        "nombre": "Milanesas a la napolitana",
        "dificultad": "media",
        "tiempo_minutos": 45,
        "porciones": 3,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("carne", 600, "g"),
            ing("huevo", 2, "unidades"),
            ing("pan rallado", 200, "g"),
            ing("queso", 200, "g"),
            ing("salsa de tomate", 200, "ml"),
            ing("aceite", 200, "ml"),
        ],
        "ingredientes_opcionales": [
            ing("oregano", 1, "cdita"),
            ing("jamon", 100, "g"),
        ],
        "pasos": [
            paso("Batir los huevos con sal y pimienta.", 2),
            paso("Pasar las milanesas por huevo y luego por pan rallado.", 5),
            paso("Freir hasta dorar de ambos lados.", 10),
            paso("Colocar las milanesas en una fuente.", 1),
            paso("Cubrir con salsa de tomate y queso.", 2),
            paso("Gratinar al horno hasta que el queso se derrita.", 8),
        ],
    },
    {
        "nombre": "Guiso de lentejas",
        "dificultad": "facil",
        "tiempo_minutos": 50,
        "porciones": 4,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("lentejas", 400, "g"),
            ing("cebolla", 1, "unidad"),
            ing("zanahoria", 2, "unidades"),
            ing("papa", 2, "unidades"),
            ing("agua", 1, "l"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("chorizo", 200, "g"),
            ing("morron", 1, "unidad"),
            ing("ajo", 2, "dientes"),
        ],
        "pasos": [
            paso("Remojar las lentejas 30 minutos si son secas.", 30),
            paso("Picar todas las verduras en cubos.", 6),
            paso("Sofreir la cebolla, zanahoria y morron en una olla.", 5),
            paso("Agregar las lentejas escurridas y la papa.", 2),
            paso("Cubrir con agua y cocinar a fuego medio.", 35),
            paso("Salpimentar y servir.", 1),
        ],
    },
    {
        "nombre": "Hamburguesas caseras",
        "dificultad": "facil",
        "tiempo_minutos": 25,
        "porciones": 3,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("carne picada", 500, "g"),
            ing("cebolla", 1, "unidad"),
            ing("huevo", 1, "unidad"),
            ing("pan rallado", 50, "g"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("ajo", 1, "diente"),
            ing("perejil", 0, "al gusto"),
            ing("queso", 100, "g"),
        ],
        "pasos": [
            paso("Picar la cebolla muy finamente.", 4),
            paso("Mezclar la carne con la cebolla, huevo, pan rallado y sal.", 3),
            paso("Formar medallones del tamano deseado.", 4),
            paso("Cocinar en una sarten o plancha 4 minutos por lado.", 8),
        ],
    },
    {
        "nombre": "Pure de papas",
        "dificultad": "facil",
        "tiempo_minutos": 25,
        "porciones": 4,
        "tipo": "guarnicion",
        "ingredientes_esenciales": [
            ing("papa", 1, "kg"),
            ing("leche", 200, "ml"),
            ing("manteca", 50, "g"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("queso", 80, "g"),
        ],
        "pasos": [
            paso("Pelar las papas y cortarlas en cubos.", 5),
            paso("Hervirlas en agua con sal hasta que esten tiernas.", 18),
            paso("Escurrir y pisar las papas.", 2),
            paso("Agregar leche caliente y manteca, mezclar bien.", 2),
            paso("Salpimentar a gusto.", 1),
        ],
    },
    {
        "nombre": "Pollo a la plancha con ensalada",
        "dificultad": "facil",
        "tiempo_minutos": 25,
        "porciones": 2,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("pollo", 400, "g"),
            ing("lechuga", 0.5, "unidad"),
            ing("tomate", 2, "unidades"),
            ing("aceite", 2, "cdas"),
            ing("sal", 1, "pizca"),
        ],
        "ingredientes_opcionales": [
            ing("limon", 1, "unidad"),
            ing("zanahoria", 1, "unidad"),
        ],
        "pasos": [
            paso("Salpimentar la pechuga de pollo.", 1),
            paso("Cocinar en una plancha caliente 5-6 minutos por lado.", 12),
            paso("Mientras, preparar la ensalada con lechuga y tomate.", 5),
            paso("Servir el pollo con la ensalada y jugo de limon.", 1),
        ],
    },
    {
        "nombre": "Fideos con manteca y queso",
        "dificultad": "facil",
        "tiempo_minutos": 15,
        "porciones": 2,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("fideos", 250, "g"),
            ing("manteca", 60, "g"),
            ing("queso rallado", 80, "g"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("perejil", 0, "al gusto"),
            ing("pimienta", 1, "pizca"),
        ],
        "pasos": [
            paso("Hervir los fideos en agua con sal.", 9),
            paso("Escurrir y devolver a la olla.", 1),
            paso("Agregar la manteca y mezclar hasta que se derrita.", 1),
            paso("Sumar el queso rallado y servir.", 1),
        ],
    },
    {
        "nombre": "Arroz con leche",
        "dificultad": "facil",
        "tiempo_minutos": 35,
        "porciones": 4,
        "tipo": "merienda",
        "ingredientes_esenciales": [
            ing("arroz", 200, "g"),
            ing("leche", 1, "l"),
            ing("azucar", 150, "g"),
        ],
        "ingredientes_opcionales": [
            ing("canela", 1, "cdita"),
            ing("cascara de limon", 1, "unidad"),
            ing("vainilla", 1, "cdita"),
        ],
        "pasos": [
            paso("Lavar el arroz bajo agua fria.", 2),
            paso("En una olla, poner la leche con el azucar y opcionales.", 1),
            paso("Cuando rompa el hervor, agregar el arroz.", 5),
            paso("Cocinar a fuego bajo revolviendo cada tanto.", 25),
            paso("Cuando este cremoso, retirar y servir frio o tibio.", 2),
        ],
    },
    {
        "nombre": "Huevos fritos",
        "dificultad": "facil",
        "tiempo_minutos": 8,
        "porciones": 1,
        "tipo": "desayuno",
        "ingredientes_esenciales": [
            ing("huevo", 2, "unidades"),
            ing("aceite", 2, "cdas"),
            ing("sal", 1, "pizca"),
        ],
        "ingredientes_opcionales": [],
        "pasos": [
            paso("Calentar el aceite en una sarten chica.", 2),
            paso("Romper los huevos directo en la sarten.", 1),
            paso("Cocinar a fuego medio hasta que la clara este firme.", 4),
            paso("Salar y servir.", 1),
        ],
    },
    {
        "nombre": "Huevos duros",
        "dificultad": "facil",
        "tiempo_minutos": 15,
        "porciones": 2,
        "tipo": "guarnicion",
        "ingredientes_esenciales": [
            ing("huevo", 4, "unidades"),
            ing("agua", 1, "l"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [],
        "pasos": [
            paso("Poner los huevos en una olla con agua fria que los cubra.", 1),
            paso("Llevar a hervor.", 6),
            paso("Una vez que hierve, cocinar 8 minutos mas.", 8),
            paso("Pasar a un bol con agua fria para detener la coccion.", 2),
            paso("Pelar y servir.", 2),
        ],
    },
    {
        "nombre": "Panqueques dulces",
        "dificultad": "facil",
        "tiempo_minutos": 25,
        "porciones": 4,
        "tipo": "merienda",
        "ingredientes_esenciales": [
            ing("harina", 250, "g"),
            ing("huevo", 2, "unidades"),
            ing("leche", 500, "ml"),
            ing("sal", 1, "pizca"),
        ],
        "ingredientes_opcionales": [
            ing("azucar", 2, "cdas"),
            ing("manteca", 30, "g"),
            ing("vainilla", 1, "cdita"),
        ],
        "pasos": [
            paso("Batir los huevos con la leche.", 2),
            paso("Agregar la harina de a poco para evitar grumos.", 3),
            paso("Calentar una sarten con manteca.", 2),
            paso("Verter un cucharon de masa y cocinar 1 minuto por lado.", 15),
            paso("Rellenar con dulce de leche o lo que se prefiera.", 3),
        ],
    },
    {
        "nombre": "Sopa de calabaza",
        "dificultad": "facil",
        "tiempo_minutos": 30,
        "porciones": 3,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("calabaza", 600, "g"),
            ing("cebolla", 1, "unidad"),
            ing("papa", 1, "unidad"),
            ing("agua", 800, "ml"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("crema", 100, "ml"),
            ing("queso rallado", 30, "g"),
            ing("ajo", 1, "diente"),
        ],
        "pasos": [
            paso("Pelar y cortar la calabaza y la papa en cubos.", 6),
            paso("Sofreir la cebolla picada en una olla.", 4),
            paso("Agregar la calabaza y la papa, cubrir con agua.", 2),
            paso("Cocinar hasta que esten tiernas.", 18),
            paso("Procesar todo hasta obtener una crema.", 2),
            paso("Salpimentar y servir.", 1),
        ],
    },
    {
        "nombre": "Ensalada de garbanzos",
        "dificultad": "facil",
        "tiempo_minutos": 15,
        "porciones": 2,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("garbanzos", 400, "g"),
            ing("tomate", 2, "unidades"),
            ing("cebolla", 0.5, "unidad"),
            ing("aceite", 2, "cdas"),
            ing("vinagre", 1, "cda"),
            ing("sal", 1, "pizca"),
        ],
        "ingredientes_opcionales": [
            ing("perejil", 0, "al gusto"),
            ing("limon", 0.5, "unidad"),
        ],
        "pasos": [
            paso("Escurrir y enjuagar los garbanzos.", 2),
            paso("Cortar el tomate y la cebolla en cubos pequenos.", 4),
            paso("Mezclar todo en un bol.", 1),
            paso("Condimentar con aceite, vinagre y sal.", 1),
        ],
    },
    {
        "nombre": "Flan casero",
        "dificultad": "media",
        "tiempo_minutos": 55,
        "porciones": 6,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("leche", 500, "ml"),
            ing("huevo", 4, "unidades"),
            ing("azucar", 200, "g"),
            ing("vainilla", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("crema", 200, "ml"),
        ],
        "pasos": [
            paso("Hacer caramelo: derretir 100 g de azucar en una sarten a fuego medio hasta que tome color dorado.", 6),
            paso("Volcar el caramelo en un molde y dejar enfriar.", 2),
            paso("Batir los huevos con el resto del azucar y la vainilla.", 3),
            paso("Calentar la leche a fuego medio hasta casi hervir, sin que rompa el hervor.", 5),
            paso("Integrar la leche caliente con los huevos batiendo despacio.", 2),
            paso("Verter la mezcla sobre el caramelo y cocinar al horno a bano maria a 160 grados hasta que cuaje.", 35),
            paso("Enfriar en la heladera antes de desmoldar.", 120),
        ],
    },
    {
        "nombre": "Mousse de chocolate",
        "dificultad": "facil",
        "tiempo_minutos": 20,
        "porciones": 4,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("chocolate", 200, "g"),
            ing("crema", 300, "ml"),
            ing("huevo", 3, "unidades"),
            ing("azucar", 50, "g"),
        ],
        "ingredientes_opcionales": [
            ing("manteca", 30, "g"),
        ],
        "pasos": [
            paso("Derretir el chocolate a bano maria a fuego bajo, revolviendo hasta que este liquido.", 5),
            paso("Separar las claras de las yemas.", 2),
            paso("Batir las claras con el azucar a punto nieve.", 4),
            paso("Mezclar el chocolate tibio con las yemas.", 2),
            paso("Batir la crema a medio punto.", 3),
            paso("Integrar la crema y las claras al chocolate con movimientos envolventes.", 2),
            paso("Refrigerar al menos 2 horas antes de servir.", 120),
        ],
    },
    {
        "nombre": "Brownies",
        "dificultad": "facil",
        "tiempo_minutos": 45,
        "porciones": 8,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("chocolate", 200, "g"),
            ing("manteca", 150, "g"),
            ing("azucar", 200, "g"),
            ing("huevo", 3, "unidades"),
            ing("harina", 120, "g"),
        ],
        "ingredientes_opcionales": [
            ing("nuez", 100, "g"),
            ing("vainilla", 1, "cdita"),
        ],
        "pasos": [
            paso("Precalentar el horno a 180 grados.", 10),
            paso("Derretir la manteca con el chocolate a bano maria a fuego bajo.", 5),
            paso("Mezclar con el azucar y dejar entibiar 5 minutos.", 5),
            paso("Agregar los huevos uno a uno, mezclando bien despues de cada uno.", 2),
            paso("Sumar la harina tamizada con movimientos envolventes hasta integrar.", 2),
            paso("Verter en un molde enmantecado y hornear a 180 grados hasta que la superficie este firme pero el centro humedo.", 25),
            paso("Enfriar antes de cortar en cuadrados.", 15),
        ],
    },
    {
        "nombre": "Bananas con dulce de leche",
        "dificultad": "facil",
        "tiempo_minutos": 10,
        "porciones": 2,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("banana", 2, "unidades"),
            ing("dulce de leche", 4, "cdas"),
        ],
        "ingredientes_opcionales": [
            ing("crema", 100, "ml"),
            ing("nuez", 30, "g"),
            ing("canela", 1, "pizca"),
        ],
        "pasos": [
            paso("Cortar las bananas en rodajas o a lo largo.", 2),
            paso("Disponer en un plato y cubrir con dulce de leche.", 2),
            paso("Decorar con crema y nueces si se desea.", 2),
        ],
    },
    {
        "nombre": "Sopa de pollo",
        "dificultad": "facil",
        "tiempo_minutos": 60,
        "porciones": 4,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("pollo", 500, "g"),
            ing("zanahoria", 2, "unidades"),
            ing("cebolla", 1, "unidad"),
            ing("apio", 2, "unidades"),
            ing("agua", 2, "l"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("fideos", 100, "g"),
            ing("perejil", 0, "al gusto"),
            ing("papa", 1, "unidad"),
        ],
        "pasos": [
            paso("Cortar las verduras en cubos medianos.", 6),
            paso("Poner el pollo y las verduras en una olla grande con el agua.", 2),
            paso("Llevar a hervor a fuego alto.", 8),
            paso("Bajar a fuego medio y cocinar destapado hasta que el pollo este tierno.", 35),
            paso("Retirar el pollo, deshuesarlo y devolver la carne a la olla.", 5),
            paso("Salpimentar, agregar fideos si se desea y cocinar 8 minutos mas a fuego medio.", 8),
            paso("Servir caliente con perejil.", 1),
        ],
    },
    {
        "nombre": "Risotto de hongos",
        "dificultad": "media",
        "tiempo_minutos": 35,
        "porciones": 3,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("arroz", 300, "g"),
            ing("champignon", 250, "g"),
            ing("cebolla", 1, "unidad"),
            ing("ajo", 2, "dientes"),
            ing("caldo", 1, "l"),
            ing("queso rallado", 80, "g"),
            ing("manteca", 30, "g"),
        ],
        "ingredientes_opcionales": [
            ing("vino blanco", 100, "ml"),
            ing("perejil", 0, "al gusto"),
        ],
        "pasos": [
            paso("Picar la cebolla, el ajo y los hongos en cubos pequenos.", 6),
            paso("Sofreir cebolla y ajo en manteca a fuego medio hasta translucidos.", 4),
            paso("Sumar los hongos y cocinar a fuego medio hasta que liberen su agua.", 6),
            paso("Agregar el arroz y tostar a fuego medio hasta que este nacarado.", 2),
            paso("Ir agregando el caldo caliente de a poco, revolviendo, a fuego medio bajo.", 18),
            paso("Cuando el arroz este al dente, retirar del fuego e integrar el queso rallado.", 2),
        ],
    },
    {
        "nombre": "Empanadas de carne",
        "dificultad": "media",
        "tiempo_minutos": 70,
        "porciones": 4,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("carne picada", 500, "g"),
            ing("cebolla", 2, "unidades"),
            ing("morron", 1, "unidad"),
            ing("huevo", 2, "unidades"),
            ing("tapas de empanadas", 12, "unidades"),
            ing("sal", 1, "cdita"),
            ing("aceite", 2, "cdas"),
        ],
        "ingredientes_opcionales": [
            ing("aceitunas", 50, "g"),
            ing("pimenton", 1, "cdita"),
            ing("comino", 1, "cdita"),
        ],
        "pasos": [
            paso("Picar la cebolla y el morron en cubos pequenos.", 6),
            paso("Sofreir cebolla y morron en aceite a fuego medio hasta transparentes.", 6),
            paso("Sumar la carne picada y cocinar a fuego alto hasta que pierda color rosado.", 6),
            paso("Condimentar, retirar del fuego y dejar enfriar.", 15),
            paso("Hervir los huevos a fuego medio hasta que esten duros y picarlos.", 12),
            paso("Rellenar las tapas, cerrar haciendo el repulgue.", 10),
            paso("Hornear a 200 grados hasta que esten doradas.", 18),
        ],
    },
    {
        "nombre": "Tallarines a la bolognesa",
        "dificultad": "facil",
        "tiempo_minutos": 45,
        "porciones": 4,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("fideos", 400, "g"),
            ing("carne picada", 500, "g"),
            ing("cebolla", 1, "unidad"),
            ing("zanahoria", 1, "unidad"),
            ing("ajo", 2, "dientes"),
            ing("salsa de tomate", 500, "ml"),
            ing("queso rallado", 80, "g"),
        ],
        "ingredientes_opcionales": [
            ing("oregano", 1, "cdita"),
            ing("vino tinto", 100, "ml"),
        ],
        "pasos": [
            paso("Picar cebolla, zanahoria y ajo finamente.", 6),
            paso("Sofreir las verduras en una olla a fuego medio hasta tiernas.", 6),
            paso("Sumar la carne y dorar a fuego alto hasta que pierda color rosado.", 6),
            paso("Agregar la salsa de tomate y condimentos, cocinar a fuego bajo y tapado.", 25),
            paso("Hervir los tallarines en agua con sal hasta que esten al dente.", 9),
            paso("Servir la pasta con la salsa por encima y queso rallado.", 1),
        ],
    },
    {
        "nombre": "Tallarines a la carbonara",
        "dificultad": "media",
        "tiempo_minutos": 25,
        "porciones": 3,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("fideos", 300, "g"),
            ing("panceta", 200, "g"),
            ing("huevo", 4, "unidades"),
            ing("queso rallado", 100, "g"),
            ing("ajo", 2, "dientes"),
            ing("pimienta", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("perejil", 0, "al gusto"),
        ],
        "pasos": [
            paso("Hervir los tallarines en agua con sal a fuego alto hasta al dente.", 9),
            paso("Cortar la panceta en cubitos y dorarla en una sarten a fuego medio.", 6),
            paso("Sumar el ajo picado a la panceta y cocinar a fuego bajo 1 minuto mas.", 1),
            paso("Batir los huevos con el queso rallado y la pimienta.", 2),
            paso("Escurrir la pasta y mezclar inmediatamente con la panceta.", 1),
            paso("Fuera del fuego, integrar la mezcla de huevos revolviendo rapido para que no se cocinen.", 2),
        ],
    },
    {
        "nombre": "Pollo al curry simple",
        "dificultad": "facil",
        "tiempo_minutos": 30,
        "porciones": 3,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("pollo", 500, "g"),
            ing("cebolla", 1, "unidad"),
            ing("ajo", 2, "dientes"),
            ing("curry", 2, "cdas"),
            ing("crema", 200, "ml"),
            ing("aceite", 2, "cdas"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("arroz", 300, "g"),
            ing("jengibre", 1, "cdita"),
        ],
        "pasos": [
            paso("Cortar el pollo en cubos y salpimentar.", 4),
            paso("Picar cebolla y ajo.", 3),
            paso("Sofreir cebolla y ajo en aceite a fuego medio hasta transparentes.", 4),
            paso("Sumar el pollo y dorar a fuego alto de todos los lados.", 6),
            paso("Agregar el curry y mezclar bien 30 segundos.", 1),
            paso("Sumar la crema, bajar a fuego bajo y cocinar tapado.", 12),
        ],
    },
    {
        "nombre": "Pollo a la mostaza",
        "dificultad": "facil",
        "tiempo_minutos": 35,
        "porciones": 3,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("pollo", 500, "g"),
            ing("mostaza", 4, "cdas"),
            ing("crema", 200, "ml"),
            ing("ajo", 2, "dientes"),
            ing("aceite", 2, "cdas"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("miel", 1, "cda"),
            ing("perejil", 0, "al gusto"),
        ],
        "pasos": [
            paso("Salpimentar el pollo y picar el ajo.", 3),
            paso("Sellar el pollo en aceite a fuego alto hasta dorar.", 6),
            paso("Sumar el ajo y cocinar 1 minuto mas a fuego medio.", 1),
            paso("Mezclar la mostaza con la crema y verter sobre el pollo.", 2),
            paso("Bajar a fuego bajo, tapar y cocinar hasta que el pollo este tierno.", 20),
        ],
    },
    {
        "nombre": "Pescado al horno",
        "dificultad": "facil",
        "tiempo_minutos": 35,
        "porciones": 2,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("pescado", 400, "g"),
            ing("limon", 1, "unidad"),
            ing("ajo", 2, "dientes"),
            ing("aceite", 3, "cdas"),
            ing("perejil", 0, "al gusto"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("papa", 2, "unidades"),
            ing("tomate", 2, "unidades"),
            ing("vino blanco", 100, "ml"),
        ],
        "pasos": [
            paso("Precalentar el horno a 200 grados.", 10),
            paso("Salpimentar el pescado y disponer en una fuente.", 3),
            paso("Mezclar aceite, jugo de limon, ajo picado y perejil.", 3),
            paso("Cubrir el pescado con la mezcla.", 1),
            paso("Hornear a 200 grados hasta que la carne se desprenda con el tenedor.", 18),
        ],
    },
    {
        "nombre": "Arroz chaufa",
        "dificultad": "facil",
        "tiempo_minutos": 30,
        "porciones": 3,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("arroz", 300, "g"),
            ing("pollo", 250, "g"),
            ing("huevo", 2, "unidades"),
            ing("cebolla de verdeo", 3, "unidades"),
            ing("salsa de soja", 4, "cdas"),
            ing("aceite", 3, "cdas"),
        ],
        "ingredientes_opcionales": [
            ing("morron", 1, "unidad"),
            ing("zanahoria", 1, "unidad"),
            ing("jamon", 100, "g"),
        ],
        "pasos": [
            paso("Cocinar el arroz en agua con sal a fuego medio hasta tierno.", 14),
            paso("Cortar el pollo en cubitos chicos y saltearlo en aceite a fuego alto hasta dorar.", 6),
            paso("Batir los huevos y hacer un revuelto en la misma sarten a fuego medio.", 3),
            paso("Sumar la cebolla de verdeo picada y saltear a fuego alto 1 minuto.", 1),
            paso("Incorporar el arroz cocido y la salsa de soja, mezclar bien.", 2),
            paso("Saltear todo junto a fuego alto hasta que este caliente.", 3),
        ],
    },
    {
        "nombre": "Albondigas con salsa",
        "dificultad": "facil",
        "tiempo_minutos": 50,
        "porciones": 4,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("carne picada", 600, "g"),
            ing("huevo", 1, "unidad"),
            ing("pan rallado", 80, "g"),
            ing("ajo", 2, "dientes"),
            ing("salsa de tomate", 500, "ml"),
            ing("cebolla", 1, "unidad"),
        ],
        "ingredientes_opcionales": [
            ing("perejil", 0, "al gusto"),
            ing("queso rallado", 50, "g"),
        ],
        "pasos": [
            paso("Mezclar la carne con huevo, pan rallado, ajo picado y sal.", 4),
            paso("Formar bolitas del tamano de una nuez.", 6),
            paso("Sofreir cebolla picada en una olla a fuego medio.", 4),
            paso("Sumar la salsa de tomate y llevar a hervor a fuego medio.", 5),
            paso("Bajar a fuego bajo, agregar las albondigas y cocinar tapado.", 25),
        ],
    },
    {
        "nombre": "Noquis con salsa de tomate",
        "dificultad": "media",
        "tiempo_minutos": 60,
        "porciones": 4,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("papa", 1, "kg"),
            ing("harina", 300, "g"),
            ing("huevo", 1, "unidad"),
            ing("salsa de tomate", 500, "ml"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("queso rallado", 80, "g"),
            ing("nuez moscada", 1, "pizca"),
        ],
        "pasos": [
            paso("Hervir las papas con cascara en agua con sal a fuego medio hasta tiernas.", 25),
            paso("Pelar y pisar las papas mientras esten calientes.", 5),
            paso("Mezclar con harina, huevo y sal hasta formar una masa.", 5),
            paso("Estirar tiras y cortar los noquis al tamano deseado.", 10),
            paso("Hervir los noquis en agua con sal a fuego alto hasta que floten.", 4),
            paso("Mezclar con la salsa caliente y servir.", 2),
        ],
    },
    {
        "nombre": "Tarta de espinaca",
        "dificultad": "facil",
        "tiempo_minutos": 50,
        "porciones": 4,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("espinaca", 500, "g"),
            ing("tapa de tarta", 1, "unidad"),
            ing("huevo", 3, "unidades"),
            ing("queso", 200, "g"),
            ing("cebolla", 1, "unidad"),
            ing("crema", 100, "ml"),
        ],
        "ingredientes_opcionales": [
            ing("nuez moscada", 1, "pizca"),
            ing("queso rallado", 50, "g"),
        ],
        "pasos": [
            paso("Lavar la espinaca y blanquearla en agua hirviendo a fuego alto.", 3),
            paso("Escurrirla bien y picarla.", 3),
            paso("Sofreir cebolla picada en una sarten a fuego medio.", 5),
            paso("Mezclar la espinaca con cebolla, huevos batidos, queso y crema.", 4),
            paso("Verter sobre la tapa de tarta y hornear a 180 grados hasta dorar.", 30),
        ],
    },
    {
        "nombre": "Omelette",
        "dificultad": "facil",
        "tiempo_minutos": 10,
        "porciones": 1,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("huevo", 3, "unidades"),
            ing("manteca", 15, "g"),
            ing("queso", 50, "g"),
            ing("sal", 1, "pizca"),
        ],
        "ingredientes_opcionales": [
            ing("jamon", 50, "g"),
            ing("tomate", 1, "unidad"),
            ing("perejil", 0, "al gusto"),
        ],
        "pasos": [
            paso("Batir los huevos con sal.", 1),
            paso("Calentar manteca en una sarten antiadherente a fuego medio.", 2),
            paso("Verter los huevos y mover la sarten para distribuir.", 1),
            paso("Cuando este casi cuajado, agregar el relleno en la mitad.", 1),
            paso("Doblar y cocinar 30 segundos mas a fuego bajo.", 1),
            paso("Servir caliente.", 1),
        ],
    },
    {
        "nombre": "Crepes salados",
        "dificultad": "facil",
        "tiempo_minutos": 35,
        "porciones": 3,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("harina", 200, "g"),
            ing("huevo", 2, "unidades"),
            ing("leche", 400, "ml"),
            ing("sal", 1, "pizca"),
            ing("manteca", 30, "g"),
            ing("jamon", 150, "g"),
            ing("queso", 200, "g"),
        ],
        "ingredientes_opcionales": [
            ing("salsa blanca", 200, "ml"),
        ],
        "pasos": [
            paso("Batir huevos, leche y sal. Sumar la harina sin grumos.", 4),
            paso("Calentar una sarten con manteca a fuego medio.", 2),
            paso("Verter un cucharon de masa y cocinar 1 minuto por lado a fuego medio.", 12),
            paso("Repetir hasta terminar la masa.", 8),
            paso("Rellenar cada crepe con jamon y queso.", 5),
            paso("Calentar en sarten a fuego bajo hasta que el queso se derrita.", 4),
        ],
    },
    {
        "nombre": "Pollo a la parrilla",
        "dificultad": "facil",
        "tiempo_minutos": 30,
        "porciones": 3,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("pollo", 600, "g"),
            ing("ajo", 3, "dientes"),
            ing("limon", 1, "unidad"),
            ing("aceite", 3, "cdas"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("oregano", 1, "cdita"),
            ing("pimenton", 1, "cdita"),
        ],
        "pasos": [
            paso("Mezclar aceite, jugo de limon, ajo picado y condimentos.", 3),
            paso("Untar el pollo con la marinada y dejar reposar.", 15),
            paso("Calentar la parrilla o plancha a fuego alto.", 5),
            paso("Cocinar el pollo a fuego alto hasta dorar de un lado.", 6),
            paso("Dar vuelta y cocinar del otro lado hasta que este bien cocido.", 6),
        ],
    },
    {
        "nombre": "Bife a caballo",
        "dificultad": "facil",
        "tiempo_minutos": 20,
        "porciones": 1,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("bife", 250, "g"),
            ing("huevo", 2, "unidades"),
            ing("aceite", 2, "cdas"),
            ing("sal", 1, "pizca"),
        ],
        "ingredientes_opcionales": [
            ing("papa", 300, "g"),
            ing("ajo", 1, "diente"),
        ],
        "pasos": [
            paso("Salpimentar el bife.", 1),
            paso("Calentar aceite en una sarten a fuego alto.", 2),
            paso("Sellar el bife 3 minutos de cada lado a fuego alto.", 6),
            paso("Retirar el bife y mantener tibio.", 1),
            paso("En la misma sarten, freir los huevos a fuego medio hasta clara firme.", 4),
            paso("Servir el bife con los huevos encima.", 1),
        ],
    },
    {
        "nombre": "Tostadas francesas",
        "dificultad": "facil",
        "tiempo_minutos": 15,
        "porciones": 2,
        "tipo": "desayuno",
        "ingredientes_esenciales": [
            ing("pan", 6, "unidades"),
            ing("huevo", 2, "unidades"),
            ing("leche", 100, "ml"),
            ing("azucar", 2, "cdas"),
            ing("manteca", 30, "g"),
        ],
        "ingredientes_opcionales": [
            ing("canela", 1, "cdita"),
            ing("vainilla", 1, "cdita"),
            ing("miel", 2, "cdas"),
        ],
        "pasos": [
            paso("Batir huevos, leche, azucar y canela en un bol.", 2),
            paso("Sumergir cada rebanada de pan en la mezcla.", 3),
            paso("Calentar manteca en una sarten a fuego medio.", 2),
            paso("Cocinar las tostadas 2 minutos por lado a fuego medio hasta doradas.", 8),
        ],
    },
    {
        "nombre": "Yogur con granola y frutas",
        "dificultad": "facil",
        "tiempo_minutos": 5,
        "porciones": 1,
        "tipo": "desayuno",
        "ingredientes_esenciales": [
            ing("yogur", 200, "g"),
            ing("granola", 50, "g"),
            ing("banana", 1, "unidad"),
            ing("miel", 1, "cda"),
        ],
        "ingredientes_opcionales": [
            ing("frutilla", 100, "g"),
            ing("nuez", 30, "g"),
        ],
        "pasos": [
            paso("Cortar la banana en rodajas.", 1),
            paso("Disponer el yogur en un bol.", 1),
            paso("Cubrir con granola, fruta y miel.", 2),
        ],
    },
    {
        "nombre": "Sandwich tostado de jamon y queso",
        "dificultad": "facil",
        "tiempo_minutos": 8,
        "porciones": 1,
        "tipo": "merienda",
        "ingredientes_esenciales": [
            ing("pan", 2, "unidades"),
            ing("jamon", 80, "g"),
            ing("queso", 80, "g"),
            ing("manteca", 15, "g"),
        ],
        "ingredientes_opcionales": [
            ing("tomate", 1, "unidad"),
            ing("oregano", 1, "pizca"),
        ],
        "pasos": [
            paso("Untar el pan con manteca por fuera.", 1),
            paso("Armar el sandwich con jamon y queso adentro.", 1),
            paso("Calentar una sarten o sandwichera a fuego medio.", 2),
            paso("Cocinar 2-3 minutos por lado a fuego medio hasta dorar y derretir el queso.", 5),
        ],
    },
    {
        "nombre": "Avena cocida",
        "dificultad": "facil",
        "tiempo_minutos": 10,
        "porciones": 1,
        "tipo": "desayuno",
        "ingredientes_esenciales": [
            ing("avena", 60, "g"),
            ing("leche", 250, "ml"),
            ing("azucar", 1, "cda"),
        ],
        "ingredientes_opcionales": [
            ing("banana", 1, "unidad"),
            ing("canela", 1, "pizca"),
            ing("miel", 1, "cda"),
        ],
        "pasos": [
            paso("Calentar la leche en una olla a fuego medio.", 3),
            paso("Cuando rompa el hervor, agregar la avena y bajar a fuego bajo.", 1),
            paso("Cocinar revolviendo hasta espesar.", 5),
            paso("Servir con frutas o miel por encima.", 1),
        ],
    },
    {
        "nombre": "Tarta de manzana",
        "dificultad": "media",
        "tiempo_minutos": 70,
        "porciones": 6,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("manzana", 4, "unidades"),
            ing("tapa de tarta", 1, "unidad"),
            ing("azucar", 100, "g"),
            ing("manteca", 50, "g"),
            ing("huevo", 1, "unidad"),
            ing("canela", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("nuez", 50, "g"),
            ing("limon", 0.5, "unidad"),
        ],
        "pasos": [
            paso("Precalentar el horno a 180 grados.", 10),
            paso("Pelar y cortar las manzanas en laminas finas.", 5),
            paso("Mezclar las manzanas con azucar, canela y jugo de limon.", 2),
            paso("Colocar la tapa en una tartera y disponer las manzanas.", 4),
            paso("Repartir trozos de manteca por encima y pintar los bordes con huevo.", 2),
            paso("Hornear a 180 grados hasta que la masa este dorada.", 35),
        ],
    },
    {
        "nombre": "Alfajores de maicena",
        "dificultad": "media",
        "tiempo_minutos": 60,
        "porciones": 12,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("maicena", 200, "g"),
            ing("harina", 150, "g"),
            ing("manteca", 200, "g"),
            ing("azucar", 100, "g"),
            ing("huevo", 3, "unidades"),
            ing("dulce de leche", 400, "g"),
            ing("coco rallado", 100, "g"),
        ],
        "ingredientes_opcionales": [
            ing("vainilla", 1, "cdita"),
            ing("limon", 1, "unidad"),
        ],
        "pasos": [
            paso("Batir la manteca con el azucar hasta blanquear.", 4),
            paso("Sumar las yemas una a una integrando bien.", 2),
            paso("Agregar maicena, harina, ralladura y vainilla. Mezclar hasta formar una masa.", 4),
            paso("Estirar la masa de 1 cm de espesor y cortar discos.", 8),
            paso("Hornear a 180 grados hasta que esten apenas firmes pero blancos.", 12),
            paso("Cuando enfrien, unirlos de a dos con dulce de leche y pasar el borde por coco.", 15),
        ],
    },
    {
        "nombre": "Budin de limon",
        "dificultad": "facil",
        "tiempo_minutos": 60,
        "porciones": 8,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("harina", 250, "g"),
            ing("azucar", 200, "g"),
            ing("manteca", 150, "g"),
            ing("huevo", 3, "unidades"),
            ing("leche", 100, "ml"),
            ing("limon", 2, "unidades"),
            ing("polvo de hornear", 1, "cda"),
        ],
        "ingredientes_opcionales": [],
        "pasos": [
            paso("Precalentar el horno a 180 grados.", 10),
            paso("Batir manteca con azucar hasta blanquear.", 4),
            paso("Sumar los huevos uno por uno integrando bien.", 2),
            paso("Agregar ralladura y jugo de limon.", 1),
            paso("Incorporar harina con polvo de hornear alternando con leche.", 3),
            paso("Verter en molde enmantecado y hornear a 180 grados hasta dorar.", 40),
        ],
    },
    {
        "nombre": "Galletas de avena",
        "dificultad": "facil",
        "tiempo_minutos": 30,
        "porciones": 12,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("avena", 200, "g"),
            ing("harina", 100, "g"),
            ing("manteca", 100, "g"),
            ing("azucar", 100, "g"),
            ing("huevo", 1, "unidad"),
        ],
        "ingredientes_opcionales": [
            ing("chocolate", 100, "g"),
            ing("banana", 1, "unidad"),
            ing("canela", 1, "cdita"),
        ],
        "pasos": [
            paso("Precalentar el horno a 180 grados.", 10),
            paso("Mezclar la manteca blanda con el azucar.", 3),
            paso("Sumar el huevo y batir bien.", 1),
            paso("Incorporar avena, harina y opcionales.", 2),
            paso("Formar bolitas y aplastarlas sobre una placa.", 5),
            paso("Hornear a 180 grados hasta que los bordes esten dorados.", 12),
        ],
    },
    {
        "nombre": "Ensalada de frutas",
        "dificultad": "facil",
        "tiempo_minutos": 15,
        "porciones": 4,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("banana", 2, "unidades"),
            ing("manzana", 2, "unidades"),
            ing("naranja", 2, "unidades"),
            ing("frutilla", 200, "g"),
        ],
        "ingredientes_opcionales": [
            ing("azucar", 2, "cdas"),
            ing("limon", 0.5, "unidad"),
            ing("yogur", 200, "g"),
        ],
        "pasos": [
            paso("Lavar y cortar todas las frutas en cubos.", 8),
            paso("Mezclar en un bol grande.", 1),
            paso("Exprimir jugo de naranja por encima.", 1),
            paso("Si se desea, agregar azucar y jugo de limon.", 1),
            paso("Mezclar suavemente y servir frio.", 1),
        ],
    },
    {
        "nombre": "Helado casero de banana",
        "dificultad": "facil",
        "tiempo_minutos": 10,
        "porciones": 2,
        "tipo": "postres",
        "ingredientes_esenciales": [
            ing("banana", 3, "unidades"),
            ing("leche", 100, "ml"),
            ing("miel", 2, "cdas"),
            ing("vainilla", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("chocolate", 50, "g"),
            ing("nuez", 30, "g"),
        ],
        "pasos": [
            paso("Pelar y cortar las bananas, congelarlas previamente.", 1),
            paso("Procesar las bananas congeladas con la leche.", 3),
            paso("Sumar miel y vainilla, procesar hasta cremoso.", 2),
            paso("Servir inmediatamente como helado blando o llevar al freezer 1 hora.", 4),
        ],
    },
    {
        "nombre": "Pure de calabaza",
        "dificultad": "facil",
        "tiempo_minutos": 30,
        "porciones": 4,
        "tipo": "guarnicion",
        "ingredientes_esenciales": [
            ing("calabaza", 800, "g"),
            ing("manteca", 30, "g"),
            ing("leche", 100, "ml"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("queso rallado", 50, "g"),
            ing("nuez moscada", 1, "pizca"),
        ],
        "pasos": [
            paso("Pelar y cortar la calabaza en cubos.", 5),
            paso("Hervir en agua con sal a fuego medio hasta tierna.", 15),
            paso("Escurrir y pisar la calabaza.", 2),
            paso("Agregar manteca y leche caliente, mezclar bien.", 2),
            paso("Salpimentar y servir.", 1),
        ],
    },
    {
        "nombre": "Arroz blanco",
        "dificultad": "facil",
        "tiempo_minutos": 20,
        "porciones": 3,
        "tipo": "guarnicion",
        "ingredientes_esenciales": [
            ing("arroz", 300, "g"),
            ing("agua", 600, "ml"),
            ing("sal", 1, "cdita"),
            ing("aceite", 1, "cda"),
        ],
        "ingredientes_opcionales": [
            ing("ajo", 1, "diente"),
            ing("manteca", 15, "g"),
        ],
        "pasos": [
            paso("Lavar el arroz bajo agua fria hasta que salga clara.", 2),
            paso("En una olla, calentar el aceite a fuego medio.", 1),
            paso("Tostar el arroz a fuego medio 1 minuto.", 1),
            paso("Agregar el agua caliente con sal.", 1),
            paso("Cuando rompa el hervor, bajar a fuego minimo y tapar.", 1),
            paso("Cocinar a fuego bajo hasta que el agua se absorba.", 15),
        ],
    },
    {
        "nombre": "Verduras al vapor",
        "dificultad": "facil",
        "tiempo_minutos": 15,
        "porciones": 3,
        "tipo": "guarnicion",
        "ingredientes_esenciales": [
            ing("brocoli", 1, "unidad"),
            ing("zanahoria", 2, "unidades"),
            ing("calabacin", 1, "unidad"),
            ing("aceite", 2, "cdas"),
            ing("sal", 1, "pizca"),
        ],
        "ingredientes_opcionales": [
            ing("limon", 0.5, "unidad"),
            ing("ajo", 1, "diente"),
        ],
        "pasos": [
            paso("Lavar y cortar todas las verduras en trozos parejos.", 5),
            paso("Poner agua en una olla y llevar a hervor a fuego alto.", 5),
            paso("Colocar las verduras en un colador sobre la olla y tapar.", 1),
            paso("Cocinar al vapor a fuego medio hasta que esten tiernas pero firmes.", 8),
            paso("Servir con un chorro de aceite y sal.", 1),
        ],
    },
    {
        "nombre": "Empanadas de verdura",
        "dificultad": "media",
        "tiempo_minutos": 60,
        "porciones": 4,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("espinaca", 500, "g"),
            ing("cebolla", 2, "unidades"),
            ing("huevo", 2, "unidades"),
            ing("queso", 150, "g"),
            ing("tapas de empanadas", 12, "unidades"),
            ing("sal", 1, "cdita"),
            ing("aceite", 2, "cdas"),
        ],
        "ingredientes_opcionales": [
            ing("nuez moscada", 1, "pizca"),
            ing("salsa blanca", 100, "ml"),
        ],
        "pasos": [
            paso("Blanquear la espinaca en agua hirviendo a fuego alto.", 3),
            paso("Escurrir bien y picarla.", 3),
            paso("Sofreir cebolla picada a fuego medio en aceite hasta transparente.", 6),
            paso("Mezclar espinaca, cebolla, queso, huevo y condimentos.", 3),
            paso("Dejar enfriar y rellenar las tapas haciendo el repulgue.", 10),
            paso("Hornear a 200 grados hasta que esten doradas.", 18),
        ],
    },
    {
        "nombre": "Pizza casera",
        "dificultad": "media",
        "tiempo_minutos": 90,
        "porciones": 4,
        "tipo": "cena",
        "ingredientes_esenciales": [
            ing("harina", 500, "g"),
            ing("levadura", 25, "g"),
            ing("agua", 300, "ml"),
            ing("sal", 1, "cdita"),
            ing("aceite", 2, "cdas"),
            ing("salsa de tomate", 300, "ml"),
            ing("queso", 300, "g"),
        ],
        "ingredientes_opcionales": [
            ing("oregano", 1, "cdita"),
            ing("aceitunas", 100, "g"),
            ing("jamon", 150, "g"),
            ing("morron", 1, "unidad"),
        ],
        "pasos": [
            paso("Disolver la levadura en agua tibia con una pizca de azucar.", 5),
            paso("Mezclar la harina con sal, agregar el agua con levadura y el aceite.", 5),
            paso("Amasar hasta obtener una masa lisa y elastica.", 10),
            paso("Tapar y dejar leudar en un lugar tibio hasta que duplique el volumen.", 45),
            paso("Precalentar el horno a 220 grados.", 10),
            paso("Estirar la masa en una pizzera, cubrir con salsa de tomate y queso.", 5),
            paso("Hornear a 220 grados hasta que el queso se derrita y los bordes esten dorados.", 12),
            paso("Agregar oregano antes de servir.", 1),
        ],
    },
    {
        "nombre": "Atun con arroz",
        "dificultad": "facil",
        "tiempo_minutos": 20,
        "porciones": 2,
        "tipo": "almuerzo",
        "ingredientes_esenciales": [
            ing("atun", 1, "unidad"),
            ing("arroz", 200, "g"),
            ing("cebolla", 1, "unidad"),
            ing("aceite", 2, "cdas"),
            ing("sal", 1, "cdita"),
        ],
        "ingredientes_opcionales": [
            ing("morron", 1, "unidad"),
            ing("tomate", 1, "unidad"),
            ing("huevo", 2, "unidades"),
        ],
        "pasos": [
            paso("Cocinar el arroz en agua con sal hasta que este tierno.", 14),
            paso("Picar la cebolla y sofreir en aceite.", 4),
            paso("Agregar el atun escurrido y mezclar.", 1),
            paso("Servir sobre el arroz caliente.", 1),
        ],
    },
]


def main():
    init_db()
    insertadas = 0
    saltadas = 0
    with get_conn() as conn:
        existentes = {
            row["nombre"].lower()
            for row in conn.execute("SELECT nombre FROM recetas").fetchall()
        }

        for receta in RECETAS:
            if receta["nombre"].lower() in existentes:
                saltadas += 1
                continue
            receta["origen"] = "base"
            insertar_receta(conn, receta)
            print(f"  + {receta['nombre']}")
            insertadas += 1

    print(f"\nSeed: {insertadas} insertadas, {saltadas} ya existian.")


if __name__ == "__main__":
    main()
